{
  "swagger" : "2.0",
  "info" : {
    "description" : "The API Flyingcarpet dashboard",
    "version" : "1.0.0",
    "title" : "FC-dashboard-api"
  },
  "host" : "virtserver.swaggerhub.com",
  "basePath" : "/bneiluj/Flyingcarpet_dashboard_api/1.0.0",
  "schemes" : [ "https" ],
  "consumes" : [ "application/json" ],
  "produces" : [ "application/json" ],
  "paths" : {
    "/bounties" : {
      "get" : {
        "tags" : [ "Bounty" ],
        "description" : "returns all registered bounties",
        "operationId" : "getBounties",
        "parameters" : [ {
          "name" : "skip",
          "in" : "query",
          "description" : "number of records to skip",
          "required" : false,
          "type" : "integer",
          "format" : "int32"
        }, {
          "name" : "limit",
          "in" : "query",
          "description" : "max number of records to return",
          "required" : false,
          "type" : "integer",
          "format" : "int32"
        } ],
        "responses" : {
          "200" : {
            "description" : "All the bountys",
            "schema" : {
              "type" : "array",
              "items" : {
                "type" : "string",
                "format" : "uri",
                "example" : "http://localhost:8080/bounties"
              }
            }
          }
        }
      },
      "post" : {
        "tags" : [ "Bounty" ],
        "operationId" : "register",
        "parameters" : [ {
          "in" : "body",
          "name" : "bounty",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/BountyRegistrationInfo"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successfully registered bounty"
          }
        }
      }
    },
    "/oracles/{bountyId}/{value}" : {
      "post" : {
        "tags" : [ "Oracles" ],
        "operationId" : "setDimmer",
        "parameters" : [ {
          "name" : "bountyId",
          "in" : "path",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "value",
          "in" : "path",
          "required" : true,
          "type" : "integer",
          "maximum" : 100.0,
          "minimum" : 0,
          "format" : "int32"
        } ],
        "responses" : {
          "200" : {
            "description" : "response",
            "schema" : {
              "$ref" : "#/definitions/ApiResponse"
            }
          }
        },
        "x-swagger-router-controller" : "Oracle"
      }
    },
    "/oracles/{bountyId}/{value}/timer/{timeunit}" : {
      "post" : {
        "tags" : [ "Oracles" ],
        "description" : "sets a dimmer to a specific value on a timer",
        "operationId" : "setDimmerTimer",
        "parameters" : [ {
          "name" : "bountyId",
          "in" : "path",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "value",
          "in" : "path",
          "required" : true,
          "type" : "integer",
          "format" : "int32"
        }, {
          "name" : "timeunit",
          "in" : "path",
          "required" : true,
          "type" : "integer",
          "format" : "int32"
        }, {
          "name" : "units",
          "in" : "query",
          "required" : false,
          "type" : "string",
          "default" : "milliseconds",
          "enum" : [ "seconds", "minutes", "milliseconds" ]
        } ],
        "responses" : {
          "200" : {
            "description" : "response",
            "schema" : {
              "$ref" : "#/definitions/ApiResponse"
            }
          }
        },
        "x-swagger-router-controller" : "Oracle"
      }
    },
    "/Oracle/switches/{bountyId}" : {
      "get" : {
        "tags" : [ "Oracles" ],
        "operationId" : "getSwitchState",
        "parameters" : [ {
          "name" : "bountyId",
          "in" : "path",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "response",
            "schema" : {
              "$ref" : "#/definitions/bountyState"
            }
          }
        },
        "x-swagger-router-controller" : "Oracle"
      }
    },
    "/Oracle/switches/{bountyId}/{value}" : {
      "post" : {
        "tags" : [ "Oracles" ],
        "operationId" : "setSwitch",
        "parameters" : [ {
          "name" : "bountyId",
          "in" : "path",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "value",
          "in" : "path",
          "required" : true,
          "type" : "string",
          "enum" : [ "true", "false" ]
        } ],
        "responses" : {
          "200" : {
            "description" : "response",
            "schema" : {
              "$ref" : "#/definitions/ApiResponse"
            }
          }
        },
        "x-swagger-router-controller" : "Oracle"
      }
    },
    "/OraclesSummary" : {
      "get" : {
        "tags" : [ "Oracles" ],
        "operationId" : "getOracleSummary",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "ok",
            "schema" : {
              "$ref" : "#/definitions/OracleSummary"
            }
          }
        },
        "x-swagger-router-controller" : "Oracle"
      }
    },
    "/CarbonOffset" : {
      "get" : {
        "tags" : [ "Forestry" ],
        "operationId" : "CarbonOffsetSummary",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "ok",
            "schema" : {
              "$ref" : "#/definitions/CarbonOffsetSummary"
            }
          }
        },
        "x-swagger-router-controller" : "Forestry"
      }
    },
    "/CarbonOffset/Oracle/{days}" : {
      "get" : {
        "tags" : [ "Forestry" ],
        "operationId" : "getOracle",
        "parameters" : [ {
          "name" : "days",
          "in" : "path",
          "required" : true,
          "type" : "integer",
          "format" : "int32"
        } ],
        "responses" : {
          "200" : {
            "description" : "the Oracle",
            "schema" : {
              "$ref" : "#/definitions/OracleResponse"
            }
          }
        },
        "x-swagger-router-controller" : "Forestry"
      }
    },
    "/CarbonOffset/{zoneId}" : {
      "get" : {
        "tags" : [ "Forestry" ],
        "operationId" : "getZoneCarbonOffset",
        "parameters" : [ {
          "name" : "zoneId",
          "in" : "path",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "Zone CarbonOffset",
            "schema" : {
              "$ref" : "#/definitions/CarbonOffsetZoneStatus"
            }
          }
        },
        "x-swagger-router-controller" : "Forestry"
      }
    },
    "/CarbonOffset/{zoneId}/Carbon" : {
      "get" : {
        "tags" : [ "Forestry" ],
        "description" : "gets the state of the Carbon",
        "operationId" : "getCarbonState",
        "parameters" : [ {
          "name" : "zoneId",
          "in" : "path",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "Carbon state",
            "schema" : {
              "$ref" : "#/definitions/CarbonState"
            }
          }
        },
        "x-swagger-router-controller" : "Forestry"
      }
    },
    "/CarbonOffset/{zoneId}/Carbon/{state}" : {
      "post" : {
        "tags" : [ "Forestry" ],
        "description" : "turns the Carbon on or off",
        "operationId" : "setCarbonState",
        "parameters" : [ {
          "name" : "zoneId",
          "in" : "path",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "state",
          "in" : "path",
          "required" : true,
          "type" : "string",
          "enum" : [ "false", "true" ]
        } ],
        "responses" : {
          "200" : {
            "description" : "Status of the operation",
            "schema" : {
              "$ref" : "#/definitions/ApiResponse"
            }
          }
        },
        "x-swagger-router-controller" : "Forestry"
      }
    },
    "/zones" : {
      "get" : {
        "tags" : [ "Zones" ],
        "operationId" : "getZones",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "ok",
            "schema" : {
              "type" : "array",
              "items" : {
                "type" : "string"
              }
            }
          }
        },
        "x-swagger-router-controller" : "Zones"
      }
    },
    "/zones/{zoneId}/quiet" : {
      "get" : {
        "tags" : [ "Zones" ],
        "operationId" : "quietZone",
        "parameters" : [ {
          "name" : "zoneId",
          "in" : "path",
          "required" : true,
          "type" : "string",
          "enum" : [ "basement", "first-floor", "second-floor" ]
        } ],
        "responses" : {
          "200" : {
            "description" : "ok"
          }
        },
        "x-swagger-router-controller" : "Zones"
      }
    }
  },
  "definitions" : {
    "OracleSummary" : {
      "type" : "object",
      "properties" : {
        "zones" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/OracleZone"
          }
        },
        "zoneStatus" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/OracleZoneStatus"
          }
        }
      },
      "description" : "ok",
      "example" : {
        "zoneStatus" : [ {
          "level" : 6,
          "lastUpdate" : "2000-01-23T04:56:07.000+00:00",
          "name" : "name",
          "id" : "id"
        }, {
          "level" : 6,
          "lastUpdate" : "2000-01-23T04:56:07.000+00:00",
          "name" : "name",
          "id" : "id"
        } ],
        "zones" : [ {
          "bountyId" : 0,
          "zone" : "zone",
          "bountyType" : "dimmer",
          "name" : "name",
          "id" : "id"
        }, {
          "bountyId" : 0,
          "zone" : "zone",
          "bountyType" : "dimmer",
          "name" : "name",
          "id" : "id"
        } ]
      }
    },
    "OracleZone" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "bountyId" : {
          "type" : "integer",
          "format" : "int32"
        },
        "bountyType" : {
          "type" : "string",
          "enum" : [ "dimmer", "switch" ]
        },
        "zone" : {
          "type" : "string"
        }
      },
      "example" : {
        "bountyId" : 0,
        "zone" : "zone",
        "bountyType" : "dimmer",
        "name" : "name",
        "id" : "id"
      }
    },
    "OracleZoneStatus" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "lastUpdate" : {
          "type" : "string",
          "format" : "date-time"
        },
        "level" : {
          "type" : "integer",
          "format" : "int32"
        }
      },
      "description" : "the status of the Oracle zone.",
      "example" : {
        "level" : 6,
        "lastUpdate" : "2000-01-23T04:56:07.000+00:00",
        "name" : "name",
        "id" : "id"
      }
    },
    "CarbonOffsetSummary" : {
      "type" : "object",
      "properties" : {
        "zones" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/CarbonOffsetZone"
          }
        },
        "zoneStatus" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/CarbonOffsetZoneStatus"
          }
        }
      },
      "description" : "ok",
      "example" : {
        "zoneStatus" : [ {
          "name" : "name",
          "id" : "id",
          "units" : "fahrenheit",
          "value" : 5.962133916683182,
          "timestamp" : "2000-01-23T04:56:07.000+00:00"
        }, {
          "name" : "name",
          "id" : "id",
          "units" : "fahrenheit",
          "value" : 5.962133916683182,
          "timestamp" : "2000-01-23T04:56:07.000+00:00"
        } ],
        "zones" : [ {
          "inputPosition" : 6,
          "outputPosition" : 1,
          "zone" : "zone",
          "name" : "name",
          "id" : 0
        }, {
          "inputPosition" : 6,
          "outputPosition" : 1,
          "zone" : "zone",
          "name" : "name",
          "id" : 0
        } ]
      }
    },
    "CarbonOffsetZone" : {
      "type" : "object",
      "required" : [ "id", "name" ],
      "properties" : {
        "id" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "the unique identifier for the zone"
        },
        "name" : {
          "type" : "string"
        },
        "inputPosition" : {
          "type" : "integer",
          "format" : "int32"
        },
        "outputPosition" : {
          "type" : "integer",
          "format" : "int32"
        },
        "zone" : {
          "type" : "string"
        }
      },
      "description" : "a single CarbonOffset zone",
      "example" : {
        "inputPosition" : 6,
        "outputPosition" : 1,
        "zone" : "zone",
        "name" : "name",
        "id" : 0
      }
    },
    "CarbonOffsetZoneStatus" : {
      "type" : "object",
      "required" : [ "id", "timestamp", "value" ],
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "the unique identifier for the zone"
        },
        "name" : {
          "type" : "string",
          "description" : "the name of the zone"
        },
        "value" : {
          "type" : "number",
          "format" : "double",
          "description" : "the CarbonOffset in the zone"
        },
        "units" : {
          "type" : "string",
          "description" : "the CarbonOffset units",
          "enum" : [ "celcius", "fahrenheit" ],
          "default" : "fahrenheit"
        },
        "timestamp" : {
          "type" : "string",
          "format" : "date-time",
          "description" : "the timestamp when the CarbonOffset was measured"
        }
      },
      "description" : "status of a single zone",
      "example" : {
        "name" : "name",
        "id" : "id",
        "units" : "fahrenheit",
        "value" : 5.962133916683182,
        "timestamp" : "2000-01-23T04:56:07.000+00:00"
      }
    },
    "ApiResponse" : {
      "type" : "object",
      "properties" : {
        "code" : {
          "type" : "integer",
          "format" : "int32"
        },
        "message" : {
          "type" : "string",
          "example" : "everything is ok"
        }
      },
      "example" : {
        "code" : 0,
        "message" : "everything is ok"
      }
    },
    "CarbonState" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "state" : {
          "type" : "string"
        }
      },
      "example" : {
        "id" : "id",
        "state" : "state"
      }
    },
    "bountyState" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "lastUpdate" : {
          "type" : "string",
          "format" : "date-time"
        },
        "level" : {
          "type" : "integer",
          "format" : "int32"
        }
      },
      "example" : {
        "level" : 0,
        "lastUpdate" : "2000-01-23T04:56:07.000+00:00",
        "name" : "name",
        "id" : "id"
      }
    },
    "OracleResponse" : {
      "type" : "object",
      "properties" : {
        "Zone" : {
          "$ref" : "#/definitions/Zone"
        },
        "values" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/Oracle"
          }
        }
      },
      "example" : {
        "Zone" : {
          "country" : "country",
          "name" : "name",
          "lon" : 1.4658129805029452,
          "id" : 0,
          "lat" : 6.027456183070403
        },
        "values" : [ {
          "date" : "2000-01-23T04:56:07.000+00:00",
          "weather" : {
            "summary" : "summary",
            "icon" : "icon",
            "description" : "description"
          },
          "humidity" : 5,
          "CarbonOffset" : {
            "high" : 3.616076749251911,
            "low" : 9.301444243932576,
            "night" : 1.2315135367772556,
            "evening" : 7.386281948385884,
            "day" : 4.145608029883936,
            "morning" : 2.027123023002322
          },
          "pressure" : 5.962133916683182,
          "clouds" : 7,
          "windSpeed" : 2.3021358869347655
        }, {
          "date" : "2000-01-23T04:56:07.000+00:00",
          "weather" : {
            "summary" : "summary",
            "icon" : "icon",
            "description" : "description"
          },
          "humidity" : 5,
          "CarbonOffset" : {
            "high" : 3.616076749251911,
            "low" : 9.301444243932576,
            "night" : 1.2315135367772556,
            "evening" : 7.386281948385884,
            "day" : 4.145608029883936,
            "morning" : 2.027123023002322
          },
          "pressure" : 5.962133916683182,
          "clouds" : 7,
          "windSpeed" : 2.3021358869347655
        } ]
      }
    },
    "Oracle" : {
      "type" : "object",
      "properties" : {
        "date" : {
          "type" : "string",
          "format" : "date-time"
        },
        "pressure" : {
          "type" : "number",
          "format" : "double"
        },
        "humidity" : {
          "type" : "integer",
          "format" : "int32"
        },
        "windSpeed" : {
          "type" : "number",
          "format" : "double"
        },
        "clouds" : {
          "type" : "integer",
          "format" : "int32"
        },
        "CarbonOffset" : {
          "$ref" : "#/definitions/OracleCarbonOffset"
        },
        "weather" : {
          "$ref" : "#/definitions/WeatherOracle"
        }
      },
      "example" : {
        "date" : "2000-01-23T04:56:07.000+00:00",
        "weather" : {
          "summary" : "summary",
          "icon" : "icon",
          "description" : "description"
        },
        "humidity" : 5,
        "CarbonOffset" : {
          "high" : 3.616076749251911,
          "low" : 9.301444243932576,
          "night" : 1.2315135367772556,
          "evening" : 7.386281948385884,
          "day" : 4.145608029883936,
          "morning" : 2.027123023002322
        },
        "pressure" : 5.962133916683182,
        "clouds" : 7,
        "windSpeed" : 2.3021358869347655
      }
    },
    "Zone" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "integer",
          "format" : "int64"
        },
        "name" : {
          "type" : "string"
        },
        "lat" : {
          "type" : "number",
          "format" : "double"
        },
        "lon" : {
          "type" : "number",
          "format" : "double"
        },
        "country" : {
          "type" : "string"
        }
      },
      "example" : {
        "country" : "country",
        "name" : "name",
        "lon" : 1.4658129805029452,
        "id" : 0,
        "lat" : 6.027456183070403
      }
    },
    "OracleCarbonOffset" : {
      "type" : "object",
      "properties" : {
        "low" : {
          "type" : "number",
          "format" : "double"
        },
        "high" : {
          "type" : "number",
          "format" : "double"
        },
        "morning" : {
          "type" : "number",
          "format" : "double"
        },
        "day" : {
          "type" : "number",
          "format" : "double"
        },
        "evening" : {
          "type" : "number",
          "format" : "double"
        },
        "night" : {
          "type" : "number",
          "format" : "double"
        }
      },
      "example" : {
        "high" : 3.616076749251911,
        "low" : 9.301444243932576,
        "night" : 1.2315135367772556,
        "evening" : 7.386281948385884,
        "day" : 4.145608029883936,
        "morning" : 2.027123023002322
      }
    },
    "WeatherOracle" : {
      "type" : "object",
      "properties" : {
        "summary" : {
          "type" : "string"
        },
        "description" : {
          "type" : "string"
        },
        "icon" : {
          "type" : "string"
        }
      },
      "example" : {
        "summary" : "summary",
        "icon" : "icon",
        "description" : "description"
      }
    },
    "BountyRegistrationInfo" : {
      "type" : "object",
      "properties" : {
        "uri" : {
          "type" : "string",
          "format" : "uri",
          "example" : "http://10.0.0.220:8080"
        },
        "id" : {
          "type" : "string",
          "format" : "uuid",
          "example" : "0729a580-2240-11e6-9eb5-0002a5d5c51b"
        }
      },
      "example" : {
        "id" : "0729a580-2240-11e6-9eb5-0002a5d5c51b",
        "uri" : "http://10.0.0.220:8080"
      }
    }
  }
}